// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RssAiParser.Context;

#nullable disable

namespace RssAiParser.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230508211156_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RssAiParser.Models.OriginalNew", b =>
                {
                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titular")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Url");

                    b.ToTable("OriginalNews");
                });

            modelBuilder.Entity("RssAiParser.Models.ParsedNew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ParsingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titular")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalId");

                    b.ToTable("ParsedNews");
                });

            modelBuilder.Entity("RssAiParser.Models.ParsedNew", b =>
                {
                    b.HasOne("RssAiParser.Models.OriginalNew", "Original")
                        .WithMany("ParsedNews")
                        .HasForeignKey("OriginalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Original");
                });

            modelBuilder.Entity("RssAiParser.Models.OriginalNew", b =>
                {
                    b.Navigation("ParsedNews");
                });
#pragma warning restore 612, 618
        }
    }
}
